### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte ....

### ISSUE THREAD

**Issue by miroi** [bast/runtest#31] opened 2020-12-09 22:54 UTC
Hi Rado,

on one server I am gettimg this DIRAC-runtest problem:
~~~
76: running test: cc N2.ccpVDZ
76: Traceback (most recent call last):
76:   File "/zfs/hybrilit.jinr.ru/user/m/milias/work/software/dirac/trunk_master/test/cc_linear/test", line 22, in <module>
76:     test.run(['cc.inp'], ['N2.ccpVDZ.mol'], f, args='--gb=0.06 --ag=1.0')
76:   File "/zfs/hybrilit.jinr.ru/user/m/milias/work/software/dirac/trunk_master/test/cc_linear/../runtest_dirac.py", line 75, in run
76:     f.check(self.work_dir, '%s' % out, 'result/%s' % out, self.verbose)
76:   File "/zfs/hybrilit.jinr.ru/user/m/milias/work/software/dirac/trunk_master/test/cc_linear/../runtest_v1.py", line 547, in check
76:     _check(self.filter_list, out_name, ref_name, verbose)
76:   File "/zfs/hybrilit.jinr.ru/user/m/milias/work/software/dirac/trunk_master/test/cc_linear/../runtest_v1.py", line 310, in _check
76:     ref_filtered = filter_file(f, ref_name, open(ref_name).readlines())
76:   File "/cvmfs/hybrilit.jinr.ru/sw/slc7_x86-64/Python/v3.6.5/lib/python3.6/encodings/ascii.py", line 26, in decode
76:     return codecs.ascii_decode(input, self.errors)[0]
76: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 5220: ordinal not in range(128)
~~~

What is wrong with Python ?

**Comment by miroi** [comment] 2020-12-09 22:56
Also
~~~
97: running test: MP2 H2O
97: Traceback (most recent call last):
97:   File "/zfs/hybrilit.jinr.ru/user/m/milias/work/software/dirac/trunk_master/test/mp2_energy/test", line 16, in <module>
97:     test.run(['MP2.inp'], ['H2O.mol'], f)
97:   File "/zfs/hybrilit.jinr.ru/user/m/milias/work/software/dirac/trunk_master/test/mp2_energy/../runtest_dirac.py", line 75, in run
97:     f.check(self.work_dir, '%s' % out, 'result/%s' % out, self.verbose)
97:   File "/zfs/hybrilit.jinr.ru/user/m/milias/work/software/dirac/trunk_master/test/mp2_energy/../runtest_v1.py", line 547, in check
97:     _check(self.filter_list, out_name, ref_name, verbose)
97:   File "/zfs/hybrilit.jinr.ru/user/m/milias/work/software/dirac/trunk_master/test/mp2_energy/../runtest_v1.py", line 310, in _check
97:     ref_filtered = filter_file(f, ref_name, open(ref_name).readlines())
97:   File "/cvmfs/hybrilit.jinr.ru/sw/slc7_x86-64/Python/v3.6.5/lib/python3.6/encodings/ascii.py", line 26, in decode
97:     return codecs.ascii_decode(input, self.errors)[0]
97: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7671: ordinal not in range(128)
~~~

**Comment by bast** [comment] 2020-12-20 19:35
How can I reproduce it? Is this current `master` on DIRAC? From the trace-back it looks to me like so strange character in the reference output.

**Comment by bast** [comment] 2020-12-20 19:36
Also this is old runtest. Would it be possible that we port the test to the latest runtest? This problem might have been solved.

**Comment by bast** [comment] 2021-05-30 11:06
I am assuming this problem has been due to using older version. Closing. But please reopen if the problem is still there.

**Closed by bast** 2021-05-30 11:06 UTC

**Comment by miroi** [comment] 2021-05-30 14:24
Ad: "Also this is old runtest. Would it be possible that we port the test to the latest runtest? This problem might have been solved." ... this is runtest-in-DIRAC, is it not up-to-date for all tests ?

**Comment by bast** [comment] 2021-05-30 14:27
In DIRAC there are two. One that corresponds to this repo and one that is very old. I just checked and that particular test uses the old one.

**Comment by miroi** [comment] 2021-05-30 14:29
Ah, two different runtest versions in DIRAC... do we have a gitlab issue for that ? I would invest some work for renewing tests in DIRAC.

**Comment by bast** [comment] 2021-05-30 14:33
Not sure there is a GitLab issue.
