### ISSUE TITLE
How to test numbers where the order does not matter and the order can change?

### ISSUE THREAD

**Issue by miroi** [bast/runtest#8] opened 2016-03-03 12:46 UTC
Hi,
see this link: https://testboard.org/cdash/testDetails.php?test=7945159&build=63939
It gives the error because of the degeneracy of p-shells, what gives variously placed reference numbers, which are otherwise correct.

In situations like this for runtest comparison there will be more "configurations" of checked results. How to deal with that ?

**Comment by bast** [comment] 2016-03-03 13:25
Currently runtest cannot treat such cases. Do you have a good suggestion on how this could be solved?

**Comment by miroi** [comment] 2016-03-03 15:50
no suggestion...only replace the reference output file, what I did before a while

**Comment by bast** [comment] 2016-03-03 15:51
If you have a good suggestion about how you would like runtest to behave in such situations, then I am all ears. Until then I am closing the issue.

**Comment by miroi** [comment] 2016-03-26 16:06
Hi Rado,

now got idea: allow several output files to be checked instead of the default, one output file.

This would mean some extra parameter for *test.run()* to handle several output files. 

Comments ?

**Comment by bast** [comment] 2016-03-26 16:58
Thank you. I will think about it. Alternative is that we have the possibility to compare list of numbers where the order does not matter.

**Comment by miroi** [comment] 2017-08-20 10:28
Hi Rado,

I am in big need of this feature.  Suitable way is comparing list of numbers where the order does not matter.

**Comment by bast** [comment] 2017-09-13 10:41
OK I missed this discussion because the issue is closed. Reopening for the moment.

**Comment by bast** [comment] 2017-09-13 10:42
So what you suggest is that we compare a list and let it pass only if the set is the same but the order does not matter?

**Comment by miroi** [comment] 2017-09-13 10:43
Yes, let it checks numbers only (in specific column) without order.

**Comment by bast** [comment] 2017-09-13 10:52
I think this is a good idea and should become a new filter option.

**Closed** 2017-09-14 13:40 UTC

**Comment by bast** [comment] 2017-09-14 13:43
This can now be achieved with `ignore_order=True`.
